In [10]:
import numpy as np
from keras.models import Sequential
from keras.layers import LSTM, Dense, Bidirectional

In [11]:
from sklearn.metrics import mean_squared_error
from math import sqrt

In [34]:
def split_sequence(sequence,n_steps):
    X,y = list(),list()
    for i in range(len(sequence)):
        end = i+n_steps
        if end > len(sequence)-1:
            break
        seq_x = sequence[i:end]
        seq_y = sequence[end]
        X.append(seq_x)
        y.append(seq_y)
    return np.array(X),np.array(y)

In [35]:
data = [10, 20, 30, 40, 50, 60, 70, 80, 90]

In [36]:
n_steps = 3

In [37]:
# X contains train sequence, y the sequence to learn
# X: array([10, 20, 30])
# y: 40
X,y = split_sequence(data,n_steps)

In [38]:
n_features = 1

In [39]:
X = X.reshape(X.shape[0],X.shape[1],n_features)
"""
reshapes X from

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50],
       [40, 50, 60],
       [50, 60, 70],
       [60, 70, 80]])

to

array([[[10],
        [20],
        [30]],

       [[20],
        [30],
        [40]],

       [[30],
        [40],
        [50]],

       [[40],
        [50],
        [60]],

       [[50],
        [60],
        [70]],

       [[60],
        [70],
        [80]]])
        a
hence iteratively, x in X will be:

array([[60],
       [70],
       [80]])

"""
print()

In [47]:
model = Sequential()
n_neurons = 50
model.add(Bidirectional(LSTM(n_neurons, activation='relu', input_shape=(n_steps, n_features))))
model.add(Dense(1))
model.compile(optimizer='adam',loss='mse')

In [48]:
model.fit(X,y, epochs=200)

Epoch 1/200
6/6 [==============================] - 2s 298ms/step - loss: 4591.1582
Epoch 2/200
6/6 [==============================] - 0s 1ms/step - loss: 4462.8159
Epoch 3/200
6/6 [==============================] - 0s 2ms/step - loss: 4356.9688
Epoch 4/200
6/6 [==============================] - 0s 3ms/step - loss: 4240.3979
Epoch 5/200
6/6 [==============================] - 0s 1ms/step - loss: 4127.6421
Epoch 6/200
6/6 [==============================] - 0s 1ms/step - loss: 4016.1926
Epoch 7/200
6/6 [==============================] - 0s 991us/step - loss: 3910.7529
Epoch 8/200
6/6 [==============================] - 0s 1ms/step - loss: 3802.9514
Epoch 9/200
6/6 [==============================] - 0s 1ms/step - loss: 3693.8428
Epoch 10/200
6/6 [==============================] - 0s 1ms/step - loss: 3583.5974
Epoch 11/200
6/6 [==============================] - 0s 1ms/step - loss: 3477.7100
Epoch 12/200
6/6 [==============================] - 0s 2ms/step - loss: 3371.2090
Epoch 13/200
6/6 [===

6/6 [==============================] - 0s 2ms/step - loss: 0.4267
Epoch 104/200
6/6 [==============================] - 0s 2ms/step - loss: 0.4397
Epoch 105/200
6/6 [==============================] - 0s 2ms/step - loss: 0.4301
Epoch 106/200
6/6 [==============================] - 0s 3ms/step - loss: 0.3909
Epoch 107/200
6/6 [==============================] - 0s 1ms/step - loss: 0.3457
Epoch 108/200
6/6 [==============================] - 0s 1ms/step - loss: 0.2952
Epoch 109/200
6/6 [==============================] - 0s 2ms/step - loss: 0.2505
Epoch 110/200
6/6 [==============================] - 0s 2ms/step - loss: 0.2189
Epoch 111/200
6/6 [==============================] - 0s 2ms/step - loss: 0.2008
Epoch 112/200
6/6 [==============================] - 0s 1ms/step - loss: 0.1905
Epoch 113/200
6/6 [==============================] - 0s 2ms/step - loss: 0.1825
Epoch 114/200
6/6 [==============================] - 0s 3ms/step - loss: 0.1718
Epoch 115/200
6/6 [==============================] - 0

In [52]:
pred_x = np.array([70,80,90])
x_reshaped = pred_x.reshape(1,n_steps, n_features)

In [53]:
yhat = model.predict(x_reshaped)

In [54]:
yhat

array([[102.20274]], dtype=float32)

In [55]:
y_actual = np.array([100])

In [56]:
y_actual

array([100])

In [57]:
rms = sqrt(mean_squared_error(y_actual, yhat))


In [58]:
rms

2.2027435302734375