In [1]:
import numpy as np
from keras.models import Sequential
from keras.layers import LSTM, Dense

Using TensorFlow backend.


In [2]:
from sklearn.metrics import mean_squared_error
from math import sqrt

In [3]:
def split_sequence(sequence,n_steps):
    X,y = list(),list()
    for i in range(len(sequence)):
        end = i+n_steps
        if end > len(sequence)-1:
            break
        seq_x = sequence[i:end]
        seq_y = sequence[end]
        X.append(seq_x)
        y.append(seq_y)
    return np.array(X),np.array(y)

In [4]:
data = [10, 20, 30, 40, 50, 60, 70, 80, 90]

In [5]:
n_steps = 3

In [6]:
# X contains train sequence, y the sequence to learn
# X: array([10, 20, 30])
# y: 40
X,y = split_sequence(data,n_steps)

In [7]:
n_features = 1

In [8]:
X = X.reshape(X.shape[0],X.shape[1],n_features)
"""
reshapes X from

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50],
       [40, 50, 60],
       [50, 60, 70],
       [60, 70, 80]])

to

array([[[10],
        [20],
        [30]],

       [[20],
        [30],
        [40]],

       [[30],
        [40],
        [50]],

       [[40],
        [50],
        [60]],

       [[50],
        [60],
        [70]],

       [[60],
        [70],
        [80]]])
        a
hence iteratively, x in X will be:

array([[60],
       [70],
       [80]])

"""
print()

In [9]:
model = Sequential()
n_neurons = 50
model.add(LSTM(n_neurons, activation='relu',return_sequences=True, input_shape=(n_steps, n_features)))
model.add(LSTM(n_neurons, activation='relu'))
model.add(Dense(1))
model.compile(optimizer='adam',loss='mse')

In [10]:
model.fit(X,y, epochs=200)

Epoch 1/200
6/6 [==============================] - 1s 214ms/step - loss: 4311.8774
Epoch 2/200
6/6 [==============================] - 0s 1ms/step - loss: 4280.8101
Epoch 3/200
6/6 [==============================] - 0s 2ms/step - loss: 4238.9009
Epoch 4/200
6/6 [==============================] - 0s 2ms/step - loss: 4196.1538
Epoch 5/200
6/6 [==============================] - 0s 1ms/step - loss: 4152.6069
Epoch 6/200
6/6 [==============================] - 0s 1ms/step - loss: 4109.6274
Epoch 7/200
6/6 [==============================] - 0s 1ms/step - loss: 4066.2571
Epoch 8/200
6/6 [==============================] - 0s 1ms/step - loss: 4020.6252
Epoch 9/200
6/6 [==============================] - 0s 1ms/step - loss: 3973.5930
Epoch 10/200
6/6 [==============================] - 0s 3ms/step - loss: 3925.9617
Epoch 11/200
6/6 [==============================] - 0s 2ms/step - loss: 3874.6787
Epoch 12/200
6/6 [==============================] - 0s 3ms/step - loss: 3818.8835
Epoch 13/200
6/6 [=====

Epoch 103/200
6/6 [==============================] - 0s 2ms/step - loss: 0.1849
Epoch 104/200
6/6 [==============================] - 0s 2ms/step - loss: 0.1634
Epoch 105/200
6/6 [==============================] - 0s 2ms/step - loss: 0.1432
Epoch 106/200
6/6 [==============================] - 0s 2ms/step - loss: 0.1318
Epoch 107/200
6/6 [==============================] - 0s 2ms/step - loss: 0.1149
Epoch 108/200
6/6 [==============================] - 0s 1ms/step - loss: 0.0932
Epoch 109/200
6/6 [==============================] - 0s 2ms/step - loss: 0.0803
Epoch 110/200
6/6 [==============================] - 0s 2ms/step - loss: 0.0746
Epoch 111/200
6/6 [==============================] - 0s 2ms/step - loss: 0.0658
Epoch 112/200
6/6 [==============================] - 0s 2ms/step - loss: 0.0576
Epoch 113/200
6/6 [==============================] - 0s 2ms/step - loss: 0.0558
Epoch 114/200
6/6 [==============================] - 0s 2ms/step - loss: 0.0537
Epoch 115/200
6/6 [=====================

In [11]:
pred_x = np.array([70,80,90])
x_reshaped = pred_x.reshape(1,n_steps, n_features)

In [12]:
yhat = model.predict(x_reshaped)

In [13]:
yhat

array([[101.91918]], dtype=float32)

In [14]:
y_actual = np.array([100])

In [15]:
y_actual

array([100])

In [16]:
rms = sqrt(mean_squared_error(y_actual, yhat))


In [17]:
rms

1.9191818237304688