In [1]:
# univariate data preparation
import numpy as np
from keras.models import Sequential
from keras.layers import LSTM, Dense

Using TensorFlow backend.


In [38]:
from sklearn.metrics import mean_squared_error
from math import sqrt

In [2]:
def split_sequence(sequence,n_steps):
    X,y = list(),list()
    for i in range(len(sequence)):
        end = i+n_steps
        if end > len(sequence)-1:
            break
        seq_x = sequence[i:end]
        seq_y = sequence[end]
        X.append(seq_x)
        y.append(seq_y)
    return np.array(X),np.array(y)

In [3]:
data = [10, 20, 30, 40, 50, 60, 70, 80, 90]

In [4]:
n_steps = 3

In [18]:
# X contains train sequence, y the sequence to learn
# X: array([10, 20, 30])
# y: 40
X,y = split_sequence(data,n_steps)

In [19]:
n_features = 1

In [20]:
X

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50],
       [40, 50, 60],
       [50, 60, 70],
       [60, 70, 80]])

In [8]:
X = X.reshape(X.shape[0],X.shape[1],n_features)
"""
reshapes X from

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50],
       [40, 50, 60],
       [50, 60, 70],
       [60, 70, 80]])

to

array([[[10],
        [20],
        [30]],

       [[20],
        [30],
        [40]],

       [[30],
        [40],
        [50]],

       [[40],
        [50],
        [60]],

       [[50],
        [60],
        [70]],

       [[60],
        [70],
        [80]]])
        a
hence iteratively, x in X will be:

array([[60],
       [70],
       [80]])

"""
print()

In [12]:
model = Sequential()
n_neurons = 50
model.add(LSTM(n_neurons, activation='relu',input_shape=(n_steps, n_features)))
model.add(Dense(1))
model.compile(optimizer='adam',loss='mse')

In [13]:
model.fit(X,y, epochs=200)

Epoch 1/200
6/6 [==============================] - 1s 124ms/step - loss: 5749.6880
Epoch 2/200
6/6 [==============================] - 0s 886us/step - loss: 5691.6499
Epoch 3/200
6/6 [==============================] - 0s 1ms/step - loss: 5616.1460
Epoch 4/200
6/6 [==============================] - 0s 1ms/step - loss: 5548.9673
Epoch 5/200
6/6 [==============================] - 0s 4ms/step - loss: 5477.7319
Epoch 6/200
6/6 [==============================] - 0s 3ms/step - loss: 5408.8848
Epoch 7/200
6/6 [==============================] - 0s 3ms/step - loss: 5343.7632
Epoch 8/200
6/6 [==============================] - 0s 2ms/step - loss: 5277.6553
Epoch 9/200
6/6 [==============================] - 0s 1ms/step - loss: 5214.1309
Epoch 10/200
6/6 [==============================] - 0s 1ms/step - loss: 5152.9419
Epoch 11/200
6/6 [==============================] - 0s 1ms/step - loss: 5092.1069
Epoch 12/200
6/6 [==============================] - 0s 2ms/step - loss: 5032.4780
Epoch 13/200
6/6 [===

Epoch 102/200
6/6 [==============================] - 0s 770us/step - loss: 13.3020
Epoch 103/200
6/6 [==============================] - 0s 1ms/step - loss: 11.9302
Epoch 104/200
6/6 [==============================] - 0s 3ms/step - loss: 10.6992
Epoch 105/200
6/6 [==============================] - 0s 2ms/step - loss: 9.5983
Epoch 106/200
6/6 [==============================] - 0s 1ms/step - loss: 8.6569
Epoch 107/200
6/6 [==============================] - 0s 3ms/step - loss: 7.9526
Epoch 108/200
6/6 [==============================] - 0s 2ms/step - loss: 7.4212
Epoch 109/200
6/6 [==============================] - 0s 3ms/step - loss: 7.0003
Epoch 110/200
6/6 [==============================] - 0s 1ms/step - loss: 6.5901
Epoch 111/200
6/6 [==============================] - 0s 1ms/step - loss: 6.2406
Epoch 112/200
6/6 [==============================] - 0s 2ms/step - loss: 5.9703
Epoch 113/200
6/6 [==============================] - 0s 2ms/step - loss: 5.7645
Epoch 114/200
6/6 [================

In [33]:
X

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50],
       [40, 50, 60],
       [50, 60, 70],
       [60, 70, 80]])

In [34]:
pred_x = np.array([70,80,90])
x_reshaped = pred_x.reshape(1,n_steps, n_features)

In [36]:
yhat = model.predict(x_reshaped)

In [37]:
yhat

array([[102.47528]], dtype=float32)

In [42]:
y_actual = np.array([100])

In [43]:
y_actual

array([100])

In [44]:
rms = sqrt(mean_squared_error(y_actual, yhat))


In [45]:
rms

2.47528076171875